=== unicoast/java-curso/06-json-con-gson/players-schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "type": "array",
  "items": {
    "type": "object",
    "properties": {
      "name": {
        "type": "string",
        "minLength": 3,
        "maxLength": 50
      },
      "age": {
        "type": "integer",
        "minimum": 0
      },
      "country": {
        "type": "string"
      },
      "active": {
        "type": "boolean"
      },
      "email": {
        "type": "string",
        "format": "email"
      },
      "hobbies": {
        "type": "array",
        "items": {
          "type": "string"
        }
      },
      "grandSlams": {
        "type": "object",
        "additionalProperties": {
          "type": "integer",
          "minimum": 0
        }
      }
    },
    "required": [
      "name",
      "age",
      "country",
      "active",
      "email",
      "hobbies",
      "grandSlams"
    ]
  }
}

=== unicoast/java-curso/06-json-con-gson/players.json
[
  {
    "name": "Novak Djokovic",
    "age": 38,
    "country": "Serbia",
    "email": "djokovic@ausopen.com",
    "active": true,
    "hobbies": [
      "Ciclismo",
      "Senderismo",
      "Yoga"
    ],
    "grandSlams": {
      "US Open": 4,
      "Australian Open": 10,
      "Wimbledon": 7,
      "Roland Garros": 3
    }
  },
  {
    "name": "Rafael Nadal",
    "age": 39,
    "country": "España",
    "email": "nadal@rolandgarros.com",
    "active": false,
    "hobbies": [
      "Fútbol",
      "Pesca",
      "Golf"
    ],
    "grandSlams": {
      "US Open": 4,
      "Australian Open": 2,
      "Wimbledon": 2,
      "Roland Garros": 14
    }
  },
  {
    "name": "Roger Federer",
    "age": 44,
    "country": "Suiza",
    "email": "federer@wimbledon.com",
    "active": false,
    "hobbies": [
      "Golf",
      "Videojuegos",
      "Esquí"
    ],
    "grandSlams": {
      "US Open": 5,
      "Australian Open": 6,
      "Wimbledon": 8,
      "Roland Garros": 1
    }
  }
]
